// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.1 (Build Build 350 03/24/2010)
// Created on Sat Dec 27 11:28:33 2025

4BitMulti 4BitMulti_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.Start(Start_sig) ,	// input  Start_sig
	.A1(A1_sig) ,	// input  A1_sig
	.A2(A2_sig) ,	// input  A2_sig
	.A3(A3_sig) ,	// input  A3_sig
	.A4(A4_sig) ,	// input  A4_sig
	.B1(B1_sig) ,	// input  B1_sig
	.B2(B2_sig) ,	// input  B2_sig
	.B3(B3_sig) ,	// input  B3_sig
	.B4(B4_sig) ,	// input  B4_sig
	.M1(M1_sig) ,	// output  M1_sig
	.M2(M2_sig) ,	// output  M2_sig
	.M3(M3_sig) ,	// output  M3_sig
	.M4(M4_sig) ,	// output  M4_sig
	.M5(M5_sig) ,	// output  M5_sig
	.M6(M6_sig) ,	// output  M6_sig
	.M7(M7_sig) ,	// output  M7_sig
	.M8(M8_sig) 	// output  M8_sig
);

