// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.1 (Build Build 350 03/24/2010)
// Created on Thu Jan 01 17:55:19 2026

Sythesis_Caculator2 Sythesis_Caculator2_inst
(
	.CLEAR(CLEAR_sig) ,	// input  CLEAR_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.D0(D0_sig) ,	// input  D0_sig
	.D1(D1_sig) ,	// input  D1_sig
	.D2(D2_sig) ,	// input  D2_sig
	.D3(D3_sig) ,	// input  D3_sig
	.out40(out40_sig) ,	// output  out40_sig
	.out41(out41_sig) ,	// output  out41_sig
	.out42(out42_sig) ,	// output  out42_sig
	.out43(out43_sig) ,	// output  out43_sig
	.out10(out10_sig) ,	// output  out10_sig
	.out11(out11_sig) ,	// output  out11_sig
	.out12(out12_sig) ,	// output  out12_sig
	.out13(out13_sig) ,	// output  out13_sig
	.out20(out20_sig) ,	// output  out20_sig
	.out21(out21_sig) ,	// output  out21_sig
	.out22(out22_sig) ,	// output  out22_sig
	.out23(out23_sig) ,	// output  out23_sig
	.out30(out30_sig) ,	// output  out30_sig
	.out31(out31_sig) ,	// output  out31_sig
	.out32(out32_sig) ,	// output  out32_sig
	.out33(out33_sig) 	// output  out33_sig
);

